fix Exception in thread Thread-1:     2019-04-28T14:41:56.256676373Z Traceback (most recent call last):     2019-04-28T14:41:56.256680769Z   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner     2019-04-28T14:41:56.256684953Z     self.run()     2019-04-28T14:41:56.256688493Z   File "/usr/local/lib/python3.6/threading.py", line 864, in run     2019-04-28T14:41:56.256698061Z     self._target(*self._args, **self._kwargs)     2019-04-28T14:41:56.256701429Z TypeError: start_account() missing 1 required positional argument: 'email'